GameStore/GameStore/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Linq;
using System.Web;

namespace GameStore.Models
{
    public class Game
    {
        public int Id { get; set; }

        [Required (ErrorMessage ="Enter name of game")]
        public string Name { get; set; }

        [Required (ErrorMessage ="Enter company of game")]
        public string Company { get; set; }

        [Required (ErrorMessage ="Enter price")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Write a description of the game")]
        public string Description { get; set; }
    }
}

GameStore/GameStore/Models/GameContext.cs
using System.Data.Entity;

namespace GameStore.Models
{
    public class GameContext : DbContext
    {
        public DbSet<Game> Games { get; set; }

        public DbSet<Purchase> Purchases { get; set; }
    }
}

GameStore/GameStore/Models/GameDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Drawing;

namespace GameStore.Models
{
    public class GameDbInitializer : DropCreateDatabaseAlways<GameContext>
    {
        protected override void Seed(GameContext db)
        {
            db.Games.Add(new Game { Name = "GTA 5", Company = "Rockstar", Price = 39.99, Description = "Grand Theft Auto V is an action-adventure video game developed by Rockstar North and published by Rockstar Games." });
            db.Games.Add(new Game { Name = "Watch Dogs 2", Company = "Ubisoft", Price = 42.99, Description = "Watch Dogs 2  is an open-world action-adventure third-person video game" });
            db.Games.Add(new Game { Name = "Minecraft", Company = "Mojang", Price = 9.99, Description = "Minecraft is a sandbox video game originally created by Swedish game designer Markus 'Notch' Persson, and later fully developed and published by Mojang." });
            //db.Games.Add(new Game { Name = "Scrap Mechanic", Company = "Axolot", Price = 12.49, Description = "Scrap Mechanic is an all-new creative multiplayer sandbox game where you explore, scavenge and collect objects from all over a wide-open interactive world. " });

            base.Seed(db);
        }
    }
}

GameStore/GameStore/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameStore.Models
{
    public class Purchase
    {
        public int PurchaseId { get; set; }

        public string GameName { get; set; }

        public DateTime Date { get; set; }

        public string Email { get; set; }

        public string Message { get; set; }

        public string PaymentMethod { get; set; }
    }
}

GameStore/GameStore/Models/UserAccess.cs
namespace GameStore.Models
{
    public class UserAccess
    {
        public static bool Admin { get; set; }

        public static string SetAccess()
        {
            if (Admin)
                return "Go to buyer";
            else
                return "Go to admin";
        }
    }
}

GameStore/GameStore/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Models;
using System.Data.Entity;
using System.Drawing;

namespace GameStore.Controllers
{
    public class GameController : Controller
    {
        GameContext db = new GameContext();

        public ActionResult Index()
        {
            IEnumerable<Game> games = db.Games;

            ViewBag.Games = games;

            ViewBag.UserAccess = UserAccess.SetAccess();

            return View();
        }

        [HttpGet]
        public ActionResult Buy(string name)
        {
            ViewBag.BuyName = name;

            return View(new Purchase() { GameName = name });
        }

        [HttpPost]
        public ActionResult Buy(Purchase purchase)
        {
            purchase.Date = DateTime.Now;

            db.Purchases.Add(purchase);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChangeUser()
        {
            UserAccess.Admin = !UserAccess.Admin;

            ViewBag.UserAccess = UserAccess.SetAccess();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Game game = db.Games.Find(id);

            return View(game);
        }

        [HttpPost]
        public ActionResult Edit(Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(game);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(game);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Game g = db.Games.Find(id);

            if (g != null)
            {
                db.Games.Remove(g);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

GameStore/GameStore/Controllers/PianomaniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameStore.Controllers
{
    public class PianomaniaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
    }
}

GameStore/GameStore/Views/Game/Buy.cshtml
@model GameStore.Models.Purchase

@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-lg-push-3 col-lg-6" style="padding-top: 30px">
        @using (Html.BeginForm("Buy", "Game", FormMethod.Post))
        {
            string nameGame = Model.GameName != null? Model.GameName: "";

            <div class="content">
                <h3>Покупка <small>[@nameGame]</small></h3>
            </div>

            <div class="form-group">
                <label for="eMail">Ваш e-mail </label>
                <input type="text" name="Email" id="eMail" class="form-control" placeholder="Введите e-mail" />
            </div>

            <div class="form-group">
                <label for="message">Ваш отзыв</label>
                <textarea class="form-control" name="Message" placeholder="Напишите отзыв" style="height: 100px;"></textarea>
            </div>

            <div class="form-inline">
                <label for="payment" style="padding-right:5px;">Способ оплаты</label>
                <select class="form-control" name="PaymentMethod" id="payment">
                    <option>WebMoney</option>
                    <option>PayPal</option>
                    <option>Приват24</option>
                </select>
            </div>

            <div class="content" style="padding-top: 20px;">
                <button type="submit" class="btn btn-success" style="width: 250px;">Купить</button>
            </div>
        }
    </div>


</div>

GameStore/GameStore/Views/Game/Create.cshtml
@model GameStore.Models.Game

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="padding-top: 30px;">
    <div class="col-lg-push-4 col-lg-4">
        @using (Html.BeginForm("Create", "Game", FormMethod.Post))
        {
            string name = "", company = "", description = "";
            double price = 0;

            if (Model != null)
            {
                name = Model.Name != null ? Model.Name : "";
                company = Model.Company != null ? Model.Company : "";
                price = Model.Price != 0 ? Model.Price : 0;
                description = Model.Description != null ? Model.Description : "";
            }

            <form data-toggle="validator" role="form">

                <div class="content"><h3>Новая игра</h3></div>

                <div class="form-group">
                    <label for="nameGame">Название игры</label>
                    <input type="text" name="Name" value="@name" id="nameGame" class="form-control" placeholder="Введите название" required />
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="form-group">
                    <label for="gameCompany">Компания</label>
                    <input type="text" name="Company" value="@company" id="gameCompany" class="form-control" placeholder="Введите название компании" required />
                    @Html.ValidationMessageFor(model => model.Company)
                </div>

                <div class="form-group">
                    <label for="gamePrice">Цена</label>
                    <input type="text" name="Price" value="@price" id="gamePrice" class="form-control" placeholder="Введите цену" required />
                    @Html.ValidationMessageFor(model => model.Price)
                </div>

                <div class="form-group">
                    <label for="pr">Description:</label>
                    <textarea class="form-control" name="Description" placeholder="Enter description of the game" style="height: 100px;" required>@description</textarea>
                    @Html.ValidationMessageFor(model => model.Description)
                </div>

                <div style="padding-top: 10px;">
                    <button type="submit" class="btn btn-block">Добавить игру</button>
                </div>
            </form>
        }
    </div>
</div>

GameStore/GameStore/Views/Game/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model GameStore.Models.Game

<div class="container col-sm-push-4 col-sm-4">
    @using (Html.BeginForm("Edit", "Game", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        string name = "", company = "", description = "";
        double price = 0;

        if (Model != null)
        {
            name = Model.Name != null ? Model.Name : "";
            company = Model.Company != null ? Model.Company : "";
            price = Model.Price != 0 ? Model.Price : 0;
            description = Model.Description != null ? Model.Description : "";
        }

        <div class="col-sm-offset-3" style="padding-top: 30px; padding-left: 10px;"><h3>Edit <small>@name</small></h3></div>

        <div class="form-group">
            <label class="control-label col-sm-3">Name:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="Name" placeholder="Enter name" value="@name" required>
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="cmp">Company:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="cmp" name="Company" value="@company" placeholder="Enter company" required>
                @Html.ValidationMessageFor(model => model.Company)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="pr">Price:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="pr" name="Price" value="@price" placeholder="Enter price" required>
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="pr">Description:</label>
            <div class="col-sm-9">
                <textarea class="form-control" name="Description" placeholder="Enter description of the game" style="height: 100px;" required>@description</textarea>
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    }
</div>

GameStore/GameStore/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container col-sm-offset-3 col-sm-6">

    <div style="text-align: center;"><h2><label>Game Store</label></h2></div>

    @foreach (GameStore.Models.Game game in ViewBag.Games)
    {
        <div class="col-sm-12" style="background-color: white; border: 2px solid black; border-radius: 10px; margin: 10px; padding-top: 10px; padding-bottom: 10px;">
            <div class="col-sm-9">
                <h4><label>@game.Name</label></h4>
                <h5>Company: @game.Company</h5>
                <p><small>@game.Description</small></p>
            </div>

            @if (!GameStore.Models.UserAccess.Admin)
                {
                <div class="col-sm-3" style="text-align: right; padding-top: 10px;">
                    <a href="/Game/Buy?name=@game.Name" class="btn btn-success" style="width: 80%">Buy | @game.Price$</a>
                </div>
            }

            @if (GameStore.Models.UserAccess.Admin)
                {
                <div class="btn-group col-sm-3" style="text-align: right; padding-top: 10px;">
                    @Html.ActionLink("Edit", "Edit", "Game", new { id = game.Id }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Delete", "Delete", "Game", new { id = game.Id }, new { @class = "btn btn-success " })
                </div>
            }
        </div>
    }

    <div style="text-align: center">
        @if (GameStore.Models.UserAccess.Admin)
            {
            <div class="form-group">
                @Html.ActionLink("Create game", "Create", "Game", new { @class = "btn btn-success" })
                @Html.ActionLink("Status: admin", "ChangeUser", "Game", new { @class = "btn btn-success" })
            </div>
        }
        @if (!GameStore.Models.UserAccess.Admin)
            {
            @Html.ActionLink("Status: buyer", "ChangeUser", "Game", new { @class = "btn btn-success" })
        }
    </div>

</div>

GameStore/GameStore/Views/Game/Index_old.cshtml
@{
    ViewBag}

<div class="container">
    <div class="content">
        <h3>Магазин игр</h3>

        @{  string access = ViewBag.UserAccess; }
        @if (GameStore.Models.UserAccess.Admin)
        {
            @Html.ActionLink("Добавить игру", "Create", "Game", new { @class = "btn btn-default" })
        }
    </div>
    <br />
    <div>
        <div class="col-lg-push-2 col-lg-8">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><p>Название игры</p></th>
                        <th><p>Компания</p></th>
                        <th><p>Цена</p></th>
                        <th><p></p></th>
                        @if (GameStore.Models.UserAccess.Admin)
                        {
                            <th><p></p></th> }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var game in ViewBag.Games)
                    {
                        <tr>
                            <td>@g.Name</td>
                            <td>@g.Company</td>
                            <td>@g.Price$</td>
                            @if (GameStore.Models.UserAccess.Admin)
                {
                                <td>@Html.ActionLink("Редактировать", "Edit", "Game", new { id = g.Id }, new { @class = "btn btn-default btn-block" })</td>
                                <td>@Html.ActionLink("Удалить", "Delete", "Game", new { id = g.Id }, new { @class = "btn btn-default btn-block" })</td>
                            }
                            @if (!GameStore.Models.UserAccess.Admin)
                {
                                <td>@Html.ActionLink("Купить", "Buy", "Game", new { name = g.Name }, new { @class = "btn btn-default btn-block" })</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

GameStore/GameStore/Views/Pianomania/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Layout_PianoMania.cshtml";
}

<div class="container" style="padding-top: 40px;">

    <div class="col-sm-offset-4 col-sm-4">
        
        @using (Html.BeginForm("Login", "Pianomania", FormMethod.Post))
        {
            <div style="text-align: center"><h3><label>Log in</label></h3></div>

            <div class="form-group">
                <label>Email</label>
                <input type="email" placeholder="Enter email" class="form-control" name="#" required/>
            </div>

            <div class="form-group">
                <label>Password</label>
                <input type="password" placeholder="Enter password" class="form-control" name="#"  required/>
            </div>

            <div>
                <button class="btn-default btn" type="submit" style="width: 115px;">Log in</button>
                <a href="#" class="btn btn-danger" style="width: 110px;">Google</a>
                <a href="#" class="btn btn-primary" style="width: 115px;">Facebook</a>
            </div>

            <div style="padding-top: 10px">
                <h5><label>New user?</label>@Html.ActionLink(" Sign up!","Register", "Pianomania")</h5>
            </div>
        }

    </div>

</div>

GameStore/GameStore/Views/Pianomania/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/Layout_PianoMania.cshtml";
}

<div class="container" style="padding-top: 40px;">

    <div class="col-sm-offset-4 col-sm-4">
        <div style="text-align: center"><h3><label>Sign up</label></h3></div>

        @using (Html.BeginForm("Register", "Pianomania", FormMethod.Post))
        {
            @*<div class="form-group">
                    <label>Username</label>
                    <input class="form-control" name="#" placeholder="Enter username" />
                </div>*@

            <div class="form-group">
                <label>Email</label>
                <input type="email" class="form-control" name="#" placeholder="Enter your email" required/>
            </div>

            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" name="#" placeholder="Enter your password" required/>
            </div>

            <div class="form-group">
                <label>Confirm password</label>
                <input type="password" class="form-control" name="#" placeholder="Confirm your password" required/>
            </div>

            <div class="btn-group">
                <button class="btn-default btn" type="submit" style="width: 145px;">Create account</button>
                <a href="#" class="btn btn-danger" style="width: 90px;">Google</a>
                <a href="#" class="btn btn-primary" style="width: 110px;">Facebook</a>
            </div>

            <div style="padding-top: 10px;">
                <h5><label>Already have an account? </label>@Html.ActionLink(" Log in!", "Login", "Pianomania")</h5>
                <h4><small>About what gives registration</small></h4>
            </div>
        }

    </div>

</div>

GameStore/GameStore/Views/Shared/Layout_PianoMania.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    @RenderBody()
</body>

</html>

GameStore/GameStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="col-lg-push-2 col-lg-8">
            @Html.ActionLink("Главная", "Index", "Game", new { @class = "btn btn-default btn-block" })
        </div>
    </div>
    @RenderBody()
</body>

</html>